version: "3.9"

services:

  # === SuperTokens Core Service ===
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    container_name: supertokens_core
    depends_on:
      - supertokens-db
    environment:
      - POSTGRESQL_CONNECTION_URI=postgresql://postgres:${SUPERTOKENS_DB_PASSWORD}@supertokens-db:5432/supertokens
      - API_KEYS=${SUPERTOKENS_API_KEY}
    ports:
      - "3567:3567"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3567/hello"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - isl-network


  # === SuperTokens Database ===
  supertokens-db:
    image: postgres:15.2
    container_name: supertokens_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SUPERTOKENS_DB_PASSWORD}
      - POSTGRES_DB=supertokens
      - POSTGRES_HOST_AUTH_METHOD=md5
    expose:
      - 5432
    volumes:
      - supertokens-db-vol:/var/lib/postgresql/data
    networks:
      - isl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


  # === ISL ADMIN DB ===
  isl-admin-db:
    image: postgres:15.2
    container_name: isl_admin_db
    restart: always
    environment:
      - POSTGRES_USER=${ISL_ADMIN_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ISL_ADMIN_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ISL_ADMIN_POSTGRES_DATABASE}
      - POSTGRES_HOST_AUTH_METHOD=md5
    expose:
      - 5432
    volumes:
      - isl-admin-db-vol:/var/lib/postgresql/data
    networks:
      - isl-network


  # === ISL ADMIN APP ===
  isl_admin_app:
    container_name: isl_admin_app
    build:
      context: ../../admin-backend
      dockerfile: ../docker/docker_backend/Dockerfile
    restart: always
    depends_on:
      - isl-admin-db
      - supertokens
    environment:
      - ISL_ADMIN_POSTGRES_HOST=isl-admin-db
      - ISL_ADMIN_POSTGRES_PORT=${ISL_ADMIN_POSTGRES_PORT}
      - ISL_ADMIN_POSTGRES_USER=${ISL_ADMIN_POSTGRES_USER}
      - ISL_ADMIN_POSTGRES_PASSWORD=${ISL_ADMIN_POSTGRES_PASSWORD}
      - ISL_ADMIN_POSTGRES_DATABASE=${ISL_ADMIN_POSTGRES_DATABASE}

      - SUPERTOKENS_CONNECTION_URI=http://supertokens:3567
      - SUPERTOKENS_API_KEY=${SUPERTOKENS_API_KEY}

      - DOCKER_RUN=True
      - VALID_API_KEYS=${VALID_API_KEYS}

    command: uvicorn main:app --host 0.0.0.0 --port 8000

    ports:
      - "8000:8000"

    volumes:
      - isl-logs-vol:/app/logs

    networks:
      - isl-network


networks:
  isl-network:


volumes:
  supertokens-db-vol:
  isl-admin-db-vol:
  isl-logs-vol:
